household.data <- read.table("household_power_consumption.txt", header = TRUE,sep = ";", na.strings = "?")
library(dplyr)
household.data <- mutate(household.data, Date = as.Date(Date,format = "%d/%m/%Y"), Time = strptime(paste(Date,Time),format = "%Y-%m-%d %H:%M:%S"))
todays <- subset(household.data, Date >= "2007-02-01" & Date <= "2007-02-02")
png(filename = "plot4.png")
par(mfrow = c(2,2))
with(todays, plot(Time ,Global_active_power , xlab = "",ylab = "Globa Active Power", type = "l"))
with(todays,plot(Time ,Voltage , xlab = "datetime", type = "l"))
with(todays,plot(Time ,Sub_metering_1, xlab = "",ylab = "energy sub metering", type = "l"))
with(todays,points(Time ,Sub_metering_2, col = "red", type = "l"))
with(todays,points(Time ,Sub_metering_3, col = "blue", type = "l"))
legend("topright", lty = 1, col = c("black", "red","blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),bty = "n")
with(todays, plot(Time ,Global_reactive_power, xlab = "datetime" ,col = "black", type = "l"))
dev.off()
     